# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Release with debug (draft)

on:
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '11'
        cache: 'maven'
    - name: Update apt sources
      run: sudo apt-get update
    - name: Install vorbis-tools / oggenc
      run: sudo apt-get install vorbis-tools
    - name: Install webp / cwebp
      run: sudo apt-get install webp
    - name: Check CPU
      run: sudo cat /proc/cpuinfo
    - name: Build with Maven
      run: mvn -e -X -B -fae clean package github-release:github-release -DGITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} -Dmaven.javadoc.skip=true
           -DrepOwner=${{ github.repository_owner }}
           -DrepName=${{ github.event.repository.name }}
           -DrepFullName=${{ github.repository }}
           -DrepBranch=${{ github.ref_name }}
           -Dnotes=$RELEASE_NOTES
           -Dhide=true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_NOTES: ${{ github.repository_owner == 'BrokenRegistry' && 'releaseNotesBR.md' || 'releaseNotesXilmi.md' }}
